import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_STATE_ACTIONS } from "./actions";

export const GEOGRAPHIES_STATE_MODULE = {
	name: "Geographies State",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[GEOGRAPHIES_STATE_ACTIONS.CREATE_GEOGRAPHIES_STATE]: {
			name: "Create Geographies Country",
			code: GEOGRAPHIES_STATE_ACTIONS.CREATE_GEOGRAPHIES_STATE,
		},
		[GEOGRAPHIES_STATE_ACTIONS.UPDATE_GEOGRAPHIES_STATE]: {
			name: "Update Geographies Country",
			code: GEOGRAPHIES_STATE_ACTIONS.UPDATE_GEOGRAPHIES_STATE,
		},
		[GEOGRAPHIES_STATE_ACTIONS.DELETE_GEOGRAPHIES_STATE]: {
			name: "Delete Geographies Country",
			code: GEOGRAPHIES_STATE_ACTIONS.DELETE_GEOGRAPHIES_STATE,
		},
		[GEOGRAPHIES_STATE_ACTIONS.FIND_GEOGRAPHIES_STATE]: {
			name: "Find Geographies Country",
			code: GEOGRAPHIES_STATE_ACTIONS.FIND_GEOGRAPHIES_STATE,
		},
		[GEOGRAPHIES_STATE_ACTIONS.GEOGRAPHIES_STATE_IMPORT_FROM_CSV]: {
			name: "create geographies country org from csv",
			code: GEOGRAPHIES_STATE_ACTIONS.GEOGRAPHIES_STATE_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_STATE_ACTIONS.GEOGRAPHIES_STATE_EXPORT]: {
			name: "Geographies Country Export",
			code: GEOGRAPHIES_STATE_ACTIONS.GEOGRAPHIES_STATE_EXPORT,
		},
	},
};
