export enum BUDGET_TARGET_LINE_ITEM_ACTIONS {
	CREATE_BUDGET_TARGET_LINE_ITEM = "create",
	UPDATE_BUDGET_TARGET_LINE_ITEM = "update",
	DELETE_BUDGET_TARGET_LINE_ITEM = "delete",
	FIND_BUDGET_TARGET_LINE_ITEM = "find",
	BUDGET_TARGET_LINE_ITEM_CREATE_FROM_CSV = "createbudgettrackinglineitemfromcsv",
	BUDGET_TARGET_LINE_ITEM_EXPORT_TABLE = "exporttable",
}
