import { MODULE_CODES } from "../../moduleCodes";
import { BUDGET_TARGET_LINE_ITEM_ACTIONS } from "./actions";

export const BUDGET_TARGET_LINE_ITEM_MODULE = {
	name: "Budget Target Line Item",
	code: MODULE_CODES.BUDGET_TARGET_LINE_ITEM,
	actionsAvailable: {
		[BUDGET_TARGET_LINE_ITEM_ACTIONS.CREATE_BUDGET_TARGET_LINE_ITEM]: {
			name: "Create Budget Target Line Item",
			code: BUDGET_TARGET_LINE_ITEM_ACTIONS.CREATE_BUDGET_TARGET_LINE_ITEM,
		},
		[BUDGET_TARGET_LINE_ITEM_ACTIONS.UPDATE_BUDGET_TARGET_LINE_ITEM]: {
			name: "Update Budget Target Line Item",
			code: BUDGET_TARGET_LINE_ITEM_ACTIONS.UPDATE_BUDGET_TARGET_LINE_ITEM,
		},
		[BUDGET_TARGET_LINE_ITEM_ACTIONS.DELETE_BUDGET_TARGET_LINE_ITEM]: {
			name: "Delete Budget Target Line Item",
			code: BUDGET_TARGET_LINE_ITEM_ACTIONS.DELETE_BUDGET_TARGET_LINE_ITEM,
		},
		[BUDGET_TARGET_LINE_ITEM_ACTIONS.FIND_BUDGET_TARGET_LINE_ITEM]: {
			name: "Find Budget Target Line Item",
			code: BUDGET_TARGET_LINE_ITEM_ACTIONS.FIND_BUDGET_TARGET_LINE_ITEM,
		},
	},
};
