export enum GEOGRAPHIES_COUNTRY_ACTIONS {
	CREATE_GEOGRAPHIES_COUNTRY = "create",
	UPDATE_GEOGRAPHIES_COUNTRY = "update",
	DELETE_GEOGRAPHIES_COUNTRY = "delete",
	FIND_GEOGRAPHIES_COUNTRY = "find",
	GEOGRAPHIES_COUNTRY_IMPORT_FROM_CSV = "creategeographiescountryorgfromcsv",
	GEOGRAPHIES_COUNTRY_EXPORT = "exporttable",
}

// export enum DELIVERABLE_CATEGORY_ACTIONS {
// 	CREATE_DELIVERABLE_CATEGORY = "create",
// 	UPDATE_DELIVERABLE_CATEGORY = "update",
// 	DELETE_DELIVERABLE_CATEGORY = "delete",
// 	FIND_DELIVERABLE_CATEGORY = "find",
// 	DELIVERABLE_CATEGORY_IMPORT_FROM_CSV = "createdeliverablecategoryorgfromcsv",
// 	DELIVERABLE_CATEGORY_EXPORT = "exporttable",
// }
