import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_COUNTRY_ACTIONS } from "./actions";

export const GEOGRAPHIES_COUNTRY_MODULE = {
	name: "Geographies Country",
	code: MODULE_CODES.GEOGRAPHIES_COUNTRY,
	actionsAvailable: {
		[GEOGRAPHIES_COUNTRY_ACTIONS.CREATE_GEOGRAPHIES_COUNTRY]: {
			name: "Create Geographies Country",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.CREATE_GEOGRAPHIES_COUNTRY,
		},
		[GEOGRAPHIES_COUNTRY_ACTIONS.UPDATE_GEOGRAPHIES_COUNTRY]: {
			name: "Update Geographies Country",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.UPDATE_GEOGRAPHIES_COUNTRY,
		},
		[GEOGRAPHIES_COUNTRY_ACTIONS.DELETE_GEOGRAPHIES_COUNTRY]: {
			name: "Delete Geographies Country",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.DELETE_GEOGRAPHIES_COUNTRY,
		},
		[GEOGRAPHIES_COUNTRY_ACTIONS.FIND_GEOGRAPHIES_COUNTRY]: {
			name: "Find Geographies Country",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.FIND_GEOGRAPHIES_COUNTRY,
		},
		[GEOGRAPHIES_COUNTRY_ACTIONS.GEOGRAPHIES_COUNTRY_IMPORT_FROM_CSV]: {
			name: "create geographies country org from csv",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.GEOGRAPHIES_COUNTRY_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_COUNTRY_ACTIONS.GEOGRAPHIES_COUNTRY_EXPORT]: {
			name: "Geographies Country Export",
			code: GEOGRAPHIES_COUNTRY_ACTIONS.GEOGRAPHIES_COUNTRY_EXPORT,
		},
	},
};
