import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_BLOCK_ACTIONS } from "./actions";
// import { DELIVERABLE_CATEGORY_ACTIONS } from "./actions";

export const GEOGRAPHIES_BLOCK_MODULE = {
	name: "Geographies Block",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[GEOGRAPHIES_BLOCK_ACTIONS.CREATE_GEOGRAPHIES_BLOCK]: {
			name: "Create Geographies block",
			code: GEOGRAPHIES_BLOCK_ACTIONS.CREATE_GEOGRAPHIES_BLOCK,
		},
		[GEOGRAPHIES_BLOCK_ACTIONS.UPDATE_GEOGRAPHIES_BLOCK]: {
			name: "Update Geographies block",
			code: GEOGRAPHIES_BLOCK_ACTIONS.UPDATE_GEOGRAPHIES_BLOCK,
		},
		[GEOGRAPHIES_BLOCK_ACTIONS.DELETE_GEOGRAPHIES_BLOCK]: {
			name: "Delete Geographies block",
			code: GEOGRAPHIES_BLOCK_ACTIONS.DELETE_GEOGRAPHIES_BLOCK,
		},
		[GEOGRAPHIES_BLOCK_ACTIONS.FIND_GEOGRAPHIES_BLOCK]: {
			name: "Find Geographies block",
			code: GEOGRAPHIES_BLOCK_ACTIONS.FIND_GEOGRAPHIES_BLOCK,
		},
		[GEOGRAPHIES_BLOCK_ACTIONS.GEOGRAPHIES_BLOCK_IMPORT_FROM_CSV]: {
			name: "create geographies block org from csv",
			code: GEOGRAPHIES_BLOCK_ACTIONS.GEOGRAPHIES_BLOCK_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_BLOCK_ACTIONS.GEOGRAPHIES_BLOCK_EXPORT]: {
			name: "Geographies block Export",
			code: GEOGRAPHIES_BLOCK_ACTIONS.GEOGRAPHIES_BLOCK_EXPORT,
		},
	},
};
