export enum SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS {
	CREATE_SUSTAINABLE_DEVELOPMENT_GOALS = "create",
	UPDATE_SUSTAINABLE_DEVELOPMENT_GOALS = "update",
	DELETE_SUSTAINABLE_DEVELOPMENT_GOALS = "delete",
	FIND_SUSTAINABLE_DEVELOPMENT_GOALS = "find",
}
