import { MODULE_CODES } from "../../moduleCodes";
import { SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS } from "./actions";

export const SUSTAINABLE_DEVELOPMENT_GOALS_MODULE = {
	name: "Sustainable Development Goals",
	code: MODULE_CODES.SUSTAINABLE_DEVELOPMENT_GOALS,
	actionsAvailable: {
		[SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.CREATE_SUSTAINABLE_DEVELOPMENT_GOALS]: {
			name: "Create Sustainable Development Goals",
			code: SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.CREATE_SUSTAINABLE_DEVELOPMENT_GOALS,
		},
		[SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.UPDATE_SUSTAINABLE_DEVELOPMENT_GOALS]: {
			name: "Update Sustainable Development Goals",
			code: SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.UPDATE_SUSTAINABLE_DEVELOPMENT_GOALS,
		},
		[SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.DELETE_SUSTAINABLE_DEVELOPMENT_GOALS]: {
			name: "Delete Sustainable Development Goals",
			code: SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.DELETE_SUSTAINABLE_DEVELOPMENT_GOALS,
		},
		[SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.FIND_SUSTAINABLE_DEVELOPMENT_GOALS]: {
			name: "Find Sustainable Development Goals",
			code: SUSTAINABLE_DEVELOPMENT_GOALS_ACTIONS.FIND_SUSTAINABLE_DEVELOPMENT_GOALS,
		},
	},
};
