export enum GEOGRAPHIES_GRAPMPANCHAYAT_ACTIONS {
	CREATE_GEOGRAPHIES_GRAPMPANCHAYAT = "create",
	UPDATE_GEOGRAPHIES_GRAPMPANCHAYAT = "update",
	DELETE_GEOGRAPHIES_GRAPMPANCHAYAT = "delete",
	FIND_GEOGRAPHIES_GRAPMPANCHAYAT = "find",
	GEOGRAPHIES_GRAPMPANCHAYAT_IMPORT_FROM_CSV = "creategeographiesgrampanchayatorgfromcsv",
	GEOGRAPHIES_GRAPMPANCHAYAT_EXPORT = "exporttable",
}
