import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS } from "./actions";

export const GEOGRAPHIES_GRAPMPANCHAYAT_MODULE = {
	name: "Geographies Grampanchayat",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.CREATE_GEOGRAPHIES_GRAPMPANCHAYAT]: {
			name: "Create Geographies Grampanchayat",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.CREATE_GEOGRAPHIES_GRAPMPANCHAYAT,
		},
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.UPDATE_GEOGRAPHIES_GRAPMPANCHAYAT]: {
			name: "Update Geographies Grampanchayat",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.UPDATE_GEOGRAPHIES_GRAPMPANCHAYAT,
		},
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.DELETE_GEOGRAPHIES_GRAPMPANCHAYAT]: {
			name: "Delete Geographies Grampanchayat",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.DELETE_GEOGRAPHIES_GRAPMPANCHAYAT,
		},
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.FIND_GEOGRAPHIES_GRAPMPANCHAYAT]: {
			name: "Find Geographies Grampanchayat",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.FIND_GEOGRAPHIES_GRAPMPANCHAYAT,
		},
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.GEOGRAPHIES_GRAPMPANCHAYAT_IMPORT_FROM_CSV]: {
			name: "create geographies Grampanchayat org from csv",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.GEOGRAPHIES_GRAPMPANCHAYAT_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.GEOGRAPHIES_GRAPMPANCHAYAT_EXPORT]: {
			name: "Geographies Grampanchayat Export",
			code: GEOGRAPHIES_GRAMPANCHAYAT_ACTIONS.GEOGRAPHIES_GRAPMPANCHAYAT_EXPORT,
		},
	},
};
