export enum GEOGRAPHIES_VILLAGE_ACTIONS {
	CREATE_GEOGRAPHIES_VILLAGE = "create",
	UPDATE_GEOGRAPHIES_VILLAGE = "update",
	DELETE_GEOGRAPHIES_VILLAGE = "delete",
	FIND_GEOGRAPHIES_VILLAGE = "find",
	GEOGRAPHIES_VILLAGE_IMPORT_FROM_CSV = "creategeographiesvillageorgfromcsv",
	GEOGRAPHIES_VILLAGE_EXPORT = "exporttable",
}
