import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_VILLAGE_ACTIONS } from "./actions";
export const GEOGRAPHIES_VILLAGE_MODULE = {
	name: "Geographies Village",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[GEOGRAPHIES_VILLAGE_ACTIONS.CREATE_GEOGRAPHIES_VILLAGE]: {
			name: "Create Geographies Village",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.CREATE_GEOGRAPHIES_VILLAGE,
		},
		[GEOGRAPHIES_VILLAGE_ACTIONS.UPDATE_GEOGRAPHIES_VILLAGE]: {
			name: "Update Geographies Village",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.UPDATE_GEOGRAPHIES_VILLAGE,
		},
		[GEOGRAPHIES_VILLAGE_ACTIONS.DELETE_GEOGRAPHIES_VILLAGE]: {
			name: "Delete Geographies Vilage",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.DELETE_GEOGRAPHIES_VILLAGE,
		},
		[GEOGRAPHIES_VILLAGE_ACTIONS.FIND_GEOGRAPHIES_VILLAGE]: {
			name: "Find Geographies Village",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.FIND_GEOGRAPHIES_VILLAGE,
		},
		[GEOGRAPHIES_VILLAGE_ACTIONS.GEOGRAPHIES_VILLAGE_IMPORT_FROM_CSV]: {
			name: "create geographies Village org from csv",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.GEOGRAPHIES_VILLAGE_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_VILLAGE_ACTIONS.GEOGRAPHIES_VILLAGE_EXPORT]: {
			name: "Geographies Village Export",
			code: GEOGRAPHIES_VILLAGE_ACTIONS.GEOGRAPHIES_VILLAGE_EXPORT,
		},
	},
};
