export enum FINANCIAL_YEAR_DONOR_ACTIONS {
	CREATE_FINANCIAL_YEAR_DONOR = "create",
	UPDATE_FINANCIAL_YEAR_DONOR = "update",
	DELETE_FINANCIAL_YEAR_DONOR = "delete",
	FIND_FINANCIAL_YEAR_DONOR = "find",
}
