import { MODULE_CODES } from "../../moduleCodes";
import { FINANCIAL_YEAR_DONOR_ACTIONS } from "./actions";

export const FINANCIAL_YEAR_DONOR_MODULE = {
	name: "Financial Year Donor",
	code: MODULE_CODES.FINANCIAL_YEAR_DONOR,
	actionsAvailable: {
		[FINANCIAL_YEAR_DONOR_ACTIONS.CREATE_FINANCIAL_YEAR_DONOR]: {
			name: "Create Financial Year Donor",
			code: FINANCIAL_YEAR_DONOR_ACTIONS.CREATE_FINANCIAL_YEAR_DONOR,
		},
		[FINANCIAL_YEAR_DONOR_ACTIONS.UPDATE_FINANCIAL_YEAR_DONOR]: {
			name: "Update Financial Year Donor",
			code: FINANCIAL_YEAR_DONOR_ACTIONS.UPDATE_FINANCIAL_YEAR_DONOR,
		},
		[FINANCIAL_YEAR_DONOR_ACTIONS.DELETE_FINANCIAL_YEAR_DONOR]: {
			name: "Delete Financial Year Donor",
			code: FINANCIAL_YEAR_DONOR_ACTIONS.DELETE_FINANCIAL_YEAR_DONOR,
		},
		[FINANCIAL_YEAR_DONOR_ACTIONS.FIND_FINANCIAL_YEAR_DONOR]: {
			name: "Find Financial Year Donor",
			code: FINANCIAL_YEAR_DONOR_ACTIONS.FIND_FINANCIAL_YEAR_DONOR,
		},
	},
};
