export enum IMPACT_TRACKING_LINE_ITEM_ACTIONS {
	CREATE_IMPACT_TRACKING_LINE_ITEM = "create",
	UPDATE_IMPACT_TRACKING_LINE_ITEM = "update",
	DELETE_IMPACT_TRACKING_LINE_ITEM = "delete",
	FIND_IMPACT_TRACKING_LINE_ITEM = "find",
	IMPACT_TRACKING_LINE_ITEM_CREATE_FROM_CSV = "createimpacttrackinglineitemfromcsv",
	IMPACT_TRACKING_LINE_ITEM_EXPORT = "exporttable",
}
