import { MODULE_CODES } from "../../moduleCodes";
import { IMPACT_TRACKING_LINE_ITEM_ACTIONS } from "./actions";

export const IMPACT_TRACKING_LINE_ITEM_MODULE = {
	name: "Impact Tracking Line Item",
	code: MODULE_CODES.IMPACT_TRACKING_LINE_ITEM,
	actionsAvailable: {
		[IMPACT_TRACKING_LINE_ITEM_ACTIONS.CREATE_IMPACT_TRACKING_LINE_ITEM]: {
			name: "Create Impact Tracking Line Item",
			code: IMPACT_TRACKING_LINE_ITEM_ACTIONS.CREATE_IMPACT_TRACKING_LINE_ITEM,
		},
		[IMPACT_TRACKING_LINE_ITEM_ACTIONS.UPDATE_IMPACT_TRACKING_LINE_ITEM]: {
			name: "Update Impact Tracking Line Item",
			code: IMPACT_TRACKING_LINE_ITEM_ACTIONS.UPDATE_IMPACT_TRACKING_LINE_ITEM,
		},
		[IMPACT_TRACKING_LINE_ITEM_ACTIONS.DELETE_IMPACT_TRACKING_LINE_ITEM]: {
			name: "Delete Impact Tracking Line Item",
			code: IMPACT_TRACKING_LINE_ITEM_ACTIONS.DELETE_IMPACT_TRACKING_LINE_ITEM,
		},
	},
};
