export enum DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS {
	CREATE_DELIVERABLE_TRACKING_LINE_ITEM = "create",
	UPDATE_DELIVERABLE_TRACKING_LINE_ITEM = "update",
	DELETE_DELIVERABLE_TRACKING_LINE_ITEM = "delete",
	FIND_DELIVERABLE_TRACKING_LINE_ITEM = "find",
}
