import { MODULE_CODES } from "../../moduleCodes";
import { DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS } from "./actions";

export const DELIVERABLE_TRACKING_LINE_ITEM_MODULE = {
	name: "Deliverable Tracking Line Item",
	code: MODULE_CODES.DELIVERABLE_TRACKING_LINE_ITEM,
	actionsAvailable: {
		[DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.CREATE_DELIVERABLE_TRACKING_LINE_ITEM]: {
			name: "Create Deliverable Tracking Line Item",
			code: DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.CREATE_DELIVERABLE_TRACKING_LINE_ITEM,
		},
		[DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.UPDATE_DELIVERABLE_TRACKING_LINE_ITEM]: {
			name: "Update Deliverable Tracking Line Item",
			code: DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.UPDATE_DELIVERABLE_TRACKING_LINE_ITEM,
		},
		[DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.DELETE_DELIVERABLE_TRACKING_LINE_ITEM]: {
			name: "Delete Deliverable Tracking Line Item",
			code: DELIVERABLE_TRACKING_LINE_ITEM_ACTIONS.DELETE_DELIVERABLE_TRACKING_LINE_ITEM,
		},
	},
};
