export enum GEOGRAPHIES_DISTRICT_ACTIONS {
	CREATE_GEOGRAPHIES_DISTRICT = "create",
	UPDATE_GEOGRAPHIES_DISTRICT = "update",
	DELETE_GEOGRAPHIES_DISTRICT = "delete",
	FIND_GEOGRAPHIES_DISTRICT = "find",
	GEOGRAPHIES_DISTRICT_IMPORT_FROM_CSV = "creategeographiesdistrictorgfromcsv",
	GEOGRAPHIES_DISTRICT_EXPORT = "exporttable",
}
