import { MODULE_CODES } from "../../moduleCodes";
import { GEOGRAPHIES_DISTRICT_ACTIONS } from "./actions";
// import { DELIVERABLE_CATEGORY_ACTIONS } from "./actions";

export const DELIVERABLE_CATEGORY_MODULE = {
	name: "Geographies district",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[GEOGRAPHIES_DISTRICT_ACTIONS.CREATE_GEOGRAPHIES_DISTRICT]: {
			name: "Create Geographies district",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.CREATE_GEOGRAPHIES_DISTRICT,
		},
		[GEOGRAPHIES_DISTRICT_ACTIONS.UPDATE_GEOGRAPHIES_DISTRICT]: {
			name: "Update Geographies district",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.UPDATE_GEOGRAPHIES_DISTRICT,
		},
		[GEOGRAPHIES_DISTRICT_ACTIONS.DELETE_GEOGRAPHIES_DISTRICT]: {
			name: "Delete Geographies district",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.DELETE_GEOGRAPHIES_DISTRICT,
		},
		[GEOGRAPHIES_DISTRICT_ACTIONS.FIND_GEOGRAPHIES_DISTRICT]: {
			name: "Find Geographies district",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.FIND_GEOGRAPHIES_DISTRICT,
		},
		[GEOGRAPHIES_DISTRICT_ACTIONS.GEOGRAPHIES_DISTRICT_IMPORT_FROM_CSV]: {
			name: "create geographies district org from csv",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.GEOGRAPHIES_DISTRICT_IMPORT_FROM_CSV,
		},
		[GEOGRAPHIES_DISTRICT_ACTIONS.GEOGRAPHIES_DISTRICT_EXPORT]: {
			name: "Geographies district Export",
			code: GEOGRAPHIES_DISTRICT_ACTIONS.GEOGRAPHIES_DISTRICT_EXPORT,
		},
	},
};
