export enum CARD_TYPES {
	PROJECT = "PROJECT",
	PROGRESS = "PROGRESS",
	PIE = "PIE",
	DEFAULT = "DEFAULT",
}

export enum CARD_OF {
	DELIVERABLE = "DELIVERABLE",
	BUDGET = "BUDGET",
	IMPACT = "IMPACT",
}
