export enum DELIVERABLE_CATEGORY_ACTIONS {
	CREATE_DELIVERABLE_CATEGORY = "create",
	UPDATE_DELIVERABLE_CATEGORY = "update",
	DELETE_DELIVERABLE_CATEGORY = "delete",
	FIND_DELIVERABLE_CATEGORY = "find",
	DELIVERABLE_CATEGORY_IMPORT_FROM_CSV = "createdeliverablecategoryorgfromcsv",
	DELIVERABLE_CATEGORY_EXPORT = "exporttable",
}
