import { MODULE_CODES } from "../../moduleCodes";
import { DELIVERABLE_CATEGORY_ACTIONS } from "./actions";

export const DELIVERABLE_CATEGORY_MODULE = {
	name: "Deliverable Category",
	code: MODULE_CODES.DELIVERABLE_CATEGORY,
	actionsAvailable: {
		[DELIVERABLE_CATEGORY_ACTIONS.CREATE_DELIVERABLE_CATEGORY]: {
			name: "Create Deliverable Category",
			code: DELIVERABLE_CATEGORY_ACTIONS.CREATE_DELIVERABLE_CATEGORY,
		},
		[DELIVERABLE_CATEGORY_ACTIONS.UPDATE_DELIVERABLE_CATEGORY]: {
			name: "Update Deliverable Category",
			code: DELIVERABLE_CATEGORY_ACTIONS.UPDATE_DELIVERABLE_CATEGORY,
		},
		[DELIVERABLE_CATEGORY_ACTIONS.DELETE_DELIVERABLE_CATEGORY]: {
			name: "Delete Deliverable Category",
			code: DELIVERABLE_CATEGORY_ACTIONS.DELETE_DELIVERABLE_CATEGORY,
		},
		[DELIVERABLE_CATEGORY_ACTIONS.FIND_DELIVERABLE_CATEGORY]: {
			name: "Find Deliverable Category",
			code: DELIVERABLE_CATEGORY_ACTIONS.FIND_DELIVERABLE_CATEGORY,
		},
	},
};
