export enum DELIVERABLE_TARGET_ACTIONS {
	CREATE_DELIVERABLE_TARGET = "create",
	UPDATE_DELIVERABLE_TARGET = "update",
	DELETE_DELIVERABLE_TARGET = "delete",
	FIND_DELIVERABLE_TARGET = "find",
	DELIVERABLE_ACHIEVED = "deliverable_achieved",
}
