import { MODULE_CODES } from "../../moduleCodes";
import { DELIVERABLE_TARGET_ACTIONS } from "./actions";

export const DELIVERABLE_TARGET_MODULE = {
	name: "Deliverable Target",
	code: MODULE_CODES.DELIVERABLE_TARGET,
	actionsAvailable: {
		[DELIVERABLE_TARGET_ACTIONS.CREATE_DELIVERABLE_TARGET]: {
			name: "Create Deliverable Target",
			code: DELIVERABLE_TARGET_ACTIONS.CREATE_DELIVERABLE_TARGET,
		},
		[DELIVERABLE_TARGET_ACTIONS.UPDATE_DELIVERABLE_TARGET]: {
			name: "Update Deliverable Target",
			code: DELIVERABLE_TARGET_ACTIONS.UPDATE_DELIVERABLE_TARGET,
		},
		[DELIVERABLE_TARGET_ACTIONS.DELETE_DELIVERABLE_TARGET]: {
			name: "Delete Deliverable Target",
			code: DELIVERABLE_TARGET_ACTIONS.DELETE_DELIVERABLE_TARGET,
		},
		[DELIVERABLE_TARGET_ACTIONS.FIND_DELIVERABLE_TARGET]: {
			name: "Find Deliverable Target",
			code: DELIVERABLE_TARGET_ACTIONS.FIND_DELIVERABLE_TARGET,
		},
		[DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_ACHIEVED]: {
			name: "Deliverable Achieved",
			code: DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_ACHIEVED,
		},
		[DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_IMPORT_FROM_CSV]: {
			name: "Deliverable Import From Csv",
			code: DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_IMPORT_FROM_CSV,
		},
		[DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_EXPORT]: {
			name: "Deliverable Export",
			code: DELIVERABLE_TARGET_ACTIONS.DELIVERABLE_EXPORT,
		},
	},
};
