name: Continuous Integration

on:
    push:
      branches:  
      - master
      - automation/CI
    
    pull_request:
      branches: [ master ]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Run test and generate coverage report
        run: yarn test --coverage --watchAll=false --passWithNoTests
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.3
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        with: 
            projectBaseDir: .
