name: Continuous Integration

on:
    push:
      branches:  
      - master
      - automation/CI
    
    pull_request:
      branches: 
         - master
         - automation/CI
         - development
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - name: Run test and generate coverage report
        run: npm run test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        

